/**
 * generated by Xtext 2.16.0
 */
package org.jactr.io2.jactr.ui.labeling;

import org.eclipse.xtext.resource.IEObjectDescription;
import org.eclipse.xtext.ui.label.DefaultDescriptionLabelProvider;

/**
 * Provides labels for IEObjectDescriptions and IResourceDescriptions.
 * 
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#label-provider
 */
@SuppressWarnings("all")
public class ModelFragmentDescriptionLabelProvider extends DefaultDescriptionLabelProvider {
  private final String IMAGE_HOME = "basic/";
  
  @Override
  public Object image(final IEObjectDescription ele) {
    String _name = ele.getEClass().getName();
    if (_name != null) {
      switch (_name) {
        case "ChunkType":
          return (this.IMAGE_HOME + "chunktype.gif");
        case "ChunkDef":
          return (this.IMAGE_HOME + "chunk.gif");
        case "Production":
          return (this.IMAGE_HOME + "production.gif");
        case "Buffer":
          return (this.IMAGE_HOME + "buffer.gif");
        default:
          return super.image(ele);
      }
    } else {
      return super.image(ele);
    }
  }
}
