/**
 * generated by Xtext 2.33.0.M1
 */
package org.jactr.io2.jactr.modelFragment;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Buffers</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.jactr.io2.jactr.modelFragment.Buffers#getBuffers <em>Buffers</em>}</li>
 * </ul>
 *
 * @see org.jactr.io2.jactr.modelFragment.ModelFragmentPackage#getBuffers()
 * @model
 * @generated
 */
public interface Buffers extends EObject
{
  /**
   * Returns the value of the '<em><b>Buffers</b></em>' containment reference list.
   * The list contents are of type {@link org.jactr.io2.jactr.modelFragment.Buffer}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Buffers</em>' containment reference list.
   * @see org.jactr.io2.jactr.modelFragment.ModelFragmentPackage#getBuffers_Buffers()
   * @model containment="true"
   * @generated
   */
  EList<Buffer> getBuffers();

} // Buffers
