/**
 * generated by Xtext 2.33.0.M1
 */
package org.jactr.io2.jactr.modelFragment;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Buffer</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.jactr.io2.jactr.modelFragment.Buffer#getSource <em>Source</em>}</li>
 * </ul>
 *
 * @see org.jactr.io2.jactr.modelFragment.ModelFragmentPackage#getBuffer()
 * @model
 * @generated
 */
public interface Buffer extends Overridable
{
  /**
   * Returns the value of the '<em><b>Source</b></em>' reference list.
   * The list contents are of type {@link org.jactr.io2.jactr.modelFragment.ChunkDef}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Source</em>' reference list.
   * @see org.jactr.io2.jactr.modelFragment.ModelFragmentPackage#getBuffer_Source()
   * @model
   * @generated
   */
  EList<ChunkDef> getSource();

} // Buffer
