/**
 * generated by Xtext 2.25.0
 */
package org.jactr.io2.jactr.modelFragment;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Chunks</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.jactr.io2.jactr.modelFragment.Chunks#getType <em>Type</em>}</li>
 *   <li>{@link org.jactr.io2.jactr.modelFragment.Chunks#getChunks <em>Chunks</em>}</li>
 * </ul>
 *
 * @see org.jactr.io2.jactr.modelFragment.ModelFragmentPackage#getChunks()
 * @model
 * @generated
 */
public interface Chunks extends Element
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' reference.
   * @see #setType(ChunkType)
   * @see org.jactr.io2.jactr.modelFragment.ModelFragmentPackage#getChunks_Type()
   * @model
   * @generated
   */
  ChunkType getType();

  /**
   * Sets the value of the '{@link org.jactr.io2.jactr.modelFragment.Chunks#getType <em>Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' reference.
   * @see #getType()
   * @generated
   */
  void setType(ChunkType value);

  /**
   * Returns the value of the '<em><b>Chunks</b></em>' containment reference list.
   * The list contents are of type {@link org.jactr.io2.jactr.modelFragment.ChunkDef}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Chunks</em>' containment reference list.
   * @see org.jactr.io2.jactr.modelFragment.ModelFragmentPackage#getChunks_Chunks()
   * @model containment="true"
   * @generated
   */
  EList<ChunkDef> getChunks();

} // Chunks
