/**
 * generated by Xtext 2.33.0.M1
 */
package org.jactr.io2.jactr.modelFragment;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Complex Slot</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.jactr.io2.jactr.modelFragment.ModelFragmentPackage#getComplexSlot()
 * @model
 * @generated
 */
public interface ComplexSlot extends EObject
{
} // ComplexSlot
