/**
 * generated by Xtext 2.25.0
 */
package org.jactr.io2.jactr.modelFragment;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Element</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.jactr.io2.jactr.modelFragment.ModelFragmentPackage#getElement()
 * @model
 * @generated
 */
public interface Element extends EObject
{
} // Element
