/**
 * generated by Xtext 2.33.0.M1
 */
package org.jactr.io2.jactr.modelFragment;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model Extension</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.jactr.io2.jactr.modelFragment.ModelExtension#getExtensionClass <em>Extension Class</em>}</li>
 *   <li>{@link org.jactr.io2.jactr.modelFragment.ModelExtension#getParameters <em>Parameters</em>}</li>
 * </ul>
 *
 * @see org.jactr.io2.jactr.modelFragment.ModelFragmentPackage#getModelExtension()
 * @model
 * @generated
 */
public interface ModelExtension extends EObject
{
  /**
   * Returns the value of the '<em><b>Extension Class</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Extension Class</em>' attribute.
   * @see #setExtensionClass(String)
   * @see org.jactr.io2.jactr.modelFragment.ModelFragmentPackage#getModelExtension_ExtensionClass()
   * @model
   * @generated
   */
  String getExtensionClass();

  /**
   * Sets the value of the '{@link org.jactr.io2.jactr.modelFragment.ModelExtension#getExtensionClass <em>Extension Class</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Extension Class</em>' attribute.
   * @see #getExtensionClass()
   * @generated
   */
  void setExtensionClass(String value);

  /**
   * Returns the value of the '<em><b>Parameters</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parameters</em>' containment reference.
   * @see #setParameters(ParametersBlock)
   * @see org.jactr.io2.jactr.modelFragment.ModelFragmentPackage#getModelExtension_Parameters()
   * @model containment="true"
   * @generated
   */
  ParametersBlock getParameters();

  /**
   * Sets the value of the '{@link org.jactr.io2.jactr.modelFragment.ModelExtension#getParameters <em>Parameters</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Parameters</em>' containment reference.
   * @see #getParameters()
   * @generated
   */
  void setParameters(ParametersBlock value);

} // ModelExtension
