/**
 * generated by Xtext 2.25.0
 */
package org.jactr.io2.jactr.modelFragment;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Modify</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.jactr.io2.jactr.modelFragment.ModelFragmentPackage#getModify()
 * @model
 * @generated
 */
public interface Modify extends ProductionAction, SimpleSlotBlock
{
} // Modify
