/**
 * generated by Xtext 2.25.0
 */
package org.jactr.io2.jactr.modelFragment;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Not Slot</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.jactr.io2.jactr.modelFragment.ModelFragmentPackage#getNotSlot()
 * @model
 * @generated
 */
public interface NotSlot extends BooleanOperation
{
} // NotSlot
