/**
 * generated by Xtext 2.25.0
 */
package org.jactr.io2.jactr.modelFragment;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Or Slot</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.jactr.io2.jactr.modelFragment.ModelFragmentPackage#getOrSlot()
 * @model
 * @generated
 */
public interface OrSlot extends BooleanOperation
{
} // OrSlot
