/**
 * generated by Xtext 2.25.0
 */
package org.jactr.io2.jactr.modelFragment;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Package Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.jactr.io2.jactr.modelFragment.PackageDeclaration#getName <em>Name</em>}</li>
 *   <li>{@link org.jactr.io2.jactr.modelFragment.PackageDeclaration#getImports <em>Imports</em>}</li>
 *   <li>{@link org.jactr.io2.jactr.modelFragment.PackageDeclaration#getModules <em>Modules</em>}</li>
 *   <li>{@link org.jactr.io2.jactr.modelFragment.PackageDeclaration#getExtensions <em>Extensions</em>}</li>
 *   <li>{@link org.jactr.io2.jactr.modelFragment.PackageDeclaration#getBuffers <em>Buffers</em>}</li>
 *   <li>{@link org.jactr.io2.jactr.modelFragment.PackageDeclaration#getElements <em>Elements</em>}</li>
 *   <li>{@link org.jactr.io2.jactr.modelFragment.PackageDeclaration#getParameters <em>Parameters</em>}</li>
 * </ul>
 *
 * @see org.jactr.io2.jactr.modelFragment.ModelFragmentPackage#getPackageDeclaration()
 * @model
 * @generated
 */
public interface PackageDeclaration extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.jactr.io2.jactr.modelFragment.ModelFragmentPackage#getPackageDeclaration_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.jactr.io2.jactr.modelFragment.PackageDeclaration#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Imports</b></em>' containment reference list.
   * The list contents are of type {@link org.jactr.io2.jactr.modelFragment.Import}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Imports</em>' containment reference list.
   * @see org.jactr.io2.jactr.modelFragment.ModelFragmentPackage#getPackageDeclaration_Imports()
   * @model containment="true"
   * @generated
   */
  EList<Import> getImports();

  /**
   * Returns the value of the '<em><b>Modules</b></em>' containment reference list.
   * The list contents are of type {@link org.jactr.io2.jactr.modelFragment.ModelModule}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Modules</em>' containment reference list.
   * @see org.jactr.io2.jactr.modelFragment.ModelFragmentPackage#getPackageDeclaration_Modules()
   * @model containment="true"
   * @generated
   */
  EList<ModelModule> getModules();

  /**
   * Returns the value of the '<em><b>Extensions</b></em>' containment reference list.
   * The list contents are of type {@link org.jactr.io2.jactr.modelFragment.ModelExtension}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Extensions</em>' containment reference list.
   * @see org.jactr.io2.jactr.modelFragment.ModelFragmentPackage#getPackageDeclaration_Extensions()
   * @model containment="true"
   * @generated
   */
  EList<ModelExtension> getExtensions();

  /**
   * Returns the value of the '<em><b>Buffers</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Buffers</em>' containment reference.
   * @see #setBuffers(Buffers)
   * @see org.jactr.io2.jactr.modelFragment.ModelFragmentPackage#getPackageDeclaration_Buffers()
   * @model containment="true"
   * @generated
   */
  Buffers getBuffers();

  /**
   * Sets the value of the '{@link org.jactr.io2.jactr.modelFragment.PackageDeclaration#getBuffers <em>Buffers</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Buffers</em>' containment reference.
   * @see #getBuffers()
   * @generated
   */
  void setBuffers(Buffers value);

  /**
   * Returns the value of the '<em><b>Elements</b></em>' containment reference list.
   * The list contents are of type {@link org.jactr.io2.jactr.modelFragment.Element}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Elements</em>' containment reference list.
   * @see org.jactr.io2.jactr.modelFragment.ModelFragmentPackage#getPackageDeclaration_Elements()
   * @model containment="true"
   * @generated
   */
  EList<Element> getElements();

  /**
   * Returns the value of the '<em><b>Parameters</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parameters</em>' containment reference.
   * @see #setParameters(ParametersBlock)
   * @see org.jactr.io2.jactr.modelFragment.ModelFragmentPackage#getPackageDeclaration_Parameters()
   * @model containment="true"
   * @generated
   */
  ParametersBlock getParameters();

  /**
   * Sets the value of the '{@link org.jactr.io2.jactr.modelFragment.PackageDeclaration#getParameters <em>Parameters</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Parameters</em>' containment reference.
   * @see #getParameters()
   * @generated
   */
  void setParameters(ParametersBlock value);

} // PackageDeclaration
