/**
 * generated by Xtext 2.25.0
 */
package org.jactr.io2.jactr.modelFragment;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Remove</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.jactr.io2.jactr.modelFragment.ModelFragmentPackage#getRemove()
 * @model
 * @generated
 */
public interface Remove extends ProductionAction, SimpleSlotBlock
{
} // Remove
