/*
 * generated by Xtext 2.33.0.M1
 */
package org.jactr.io2.jactr.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractModelFragmentValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(org.jactr.io2.jactr.modelFragment.ModelFragmentPackage.eINSTANCE);
		return result;
	}
}
