/*
 * generated by Xtext 2.25.0
 */
package org.jactr.io2.jactr.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ModelFragmentAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/jactr/io2/jactr/parser/antlr/internal/InternalModelFragment.tokens");
	}
}
