package org.jactr.io2.jactr.ui.wizard;

import java.util.Collections;
import java.util.List;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.xbase.lib.CollectionLiterals;

@SuppressWarnings("all")
public class ModelStubs {
  public static CharSequence basicModel(final String name) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("/*");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("* The namespace defines the location of your model in a global scope.");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("* This is used when embedding other model content within a model");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("*/");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("namespace ");
    _builder.append(name, " ");
    _builder.append("{");
    _builder.newLineIfNotEmpty();
    _builder.append("/*");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("* These are the namespaces for common types and buffers. ");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("*/\t");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("import jactr.declarative.*");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("import jactr.procedural.*");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("import jactr.retrieval.*");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("import jactr.imaginal.*");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("import jactr.goal.*");
    _builder.newLine();
    _builder.append("/*");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("* modules define theoretically relevant contributions to the model. A ");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("* declarative and procedural module are the bare minimum. Note: parameters");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("* are denoted by [].");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("*/");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("module \"org.jactr.core.module.declarative.six.DefaultDeclarativeModule6\" [");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("\"ActivationNoise\"          : \"0\"");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("\"BaseLevelConstant\"        : \"0\"");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("\"EnablePartialMatching\"    : \"false\"");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("\"MaximumDifference\"        : \"-1\"");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("\"MaximumSimilarity\"        : \"0\"");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("\"MismatchPenalty\"          : \"1\"");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("\"PermanentActivationNoise\" : \"0\"]");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("module \"org.jactr.core.module.procedural.six.DefaultProceduralModule6\" [");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("\"DefaultProductionFiringTime\" : \"0.05\"");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("\"ExpectedUtilityNoise\"        : \"0\"");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("\"NumberOfProductionsFired\"    : \"0\" ]");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("module \"org.jactr.core.module.goal.six.DefaultGoalModule6\" [ ]");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("module \"org.jactr.core.module.retrieval.six.DefaultRetrievalModule6\" [");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("\"EnableIndexedRetrievals\" : \"false\"");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("\"FINSTDurationTime\"       : \"3.0\"");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("\"LatencyFactor\"           : \"1\"");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("\"NumberOfFINSTs\"          : \"4\"");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("\"RetrievalThreshold\"      : \"0\" ]");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("module \"org.jactr.core.module.random.six.DefaultRandomModule\"[]   ");
    _builder.newLine();
    _builder.append("   ");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("/**");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("* common buffers. They are @overridden because we are telling the compiler to");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("* use this particular definition and not the ones in jactr.declarative and");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("* jactr.retrieval");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("*/  ");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("buffers {");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("@Override");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("goal {} [");
    _builder.newLine();
    _builder.append("     ");
    _builder.append("\"Activation\"              : \"1\"");
    _builder.newLine();
    _builder.append("     ");
    _builder.append("\"StrictHarvestingEnabled\" : \"false\" ]");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("/*");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("* chunks and types");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("*/ ");
    _builder.newLine();
    _builder.append(" ");
    _builder.newLine();
    _builder.append("/*");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("* productions");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("*/  ");
    _builder.newLine();
    _builder.append(" ");
    _builder.newLine();
    _builder.append("}[");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("\"EnablePersistentExecution\" : \"false\"");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("\"EnableUnusedCycleSkipping\" : \"true\" //safe for internal-only models");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("]");
    _builder.newLine();
    return _builder;
  }
  
  public static List<String> basicModelDependencies() {
    return Collections.<String>unmodifiableList(CollectionLiterals.<String>newArrayList("org.jactr.core", "org.jactr.io", "org.jactr.tools", "org.jactr.tools.experiment", "org.jactr.io2.jactr"));
  }
  
  public static List<String> embodiedModelDependencies() {
    return Collections.<String>unmodifiableList(CollectionLiterals.<String>newArrayList("org.jactr.core", "org.jactr.io", "org.jactr.tools", "org.jactr.tools.experiment", "org.jactr.io2.jactr", "org.commonreality.api", "org.commonreality.sensors", "org.commonreality.sensors.xml"));
  }
  
  public static CharSequence embodiedModel(final String name) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("/*");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("* ");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("*/");
    _builder.newLine();
    _builder.append("namespace ");
    _builder.append(name);
    _builder.append("{");
    _builder.newLineIfNotEmpty();
    _builder.append(" ");
    _builder.append("import jactr.declarative.*");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("import jactr.procedural.*");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("import jactr.retrieval.*");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("import jactr.imaginal.*");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("import jactr.visual.*");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("import jactr.motor.*");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("import jactr.aural.*");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("import jactr.vocal.*");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("import jactr.goal.*");
    _builder.newLine();
    _builder.append("    ");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("module \"org.jactr.core.module.declarative.six.DefaultDeclarativeModule6\" [");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("\"ActivationNoise\"          : \"0\"");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("\"BaseLevelConstant\"        : \"0\"");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("\"EnablePartialMatching\"    : \"false\"");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("\"MaximumDifference\"        : \"-1\"");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("\"MaximumSimilarity\"        : \"0\"");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("\"MismatchPenalty\"          : \"1\"");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("\"PermanentActivationNoise\" : \"0\"]");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("module \"org.jactr.core.module.procedural.six.DefaultProceduralModule6\" [");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("\"DefaultProductionFiringTime\" : \"0.05\"");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("\"ExpectedUtilityNoise\"        : \"0\"");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("\"NumberOfProductionsFired\"    : \"0\" ]");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("module \"org.jactr.core.module.goal.six.DefaultGoalModule6\" []");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("module \"org.jactr.core.module.retrieval.six.DefaultRetrievalModule6\" [");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("\"FINSTDurationTime\"       : \"3.0\"");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("\"LatencyFactor\"           : \"1\"");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("\"NumberOfFINSTs\"          : \"4\"");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("\"RetrievalThreshold\"      : \"0\" ]");
    _builder.newLine();
    _builder.append("module \"org.jactr.core.module.imaginal.six.DefaultImaginalModule6\"[]");
    _builder.newLine();
    _builder.append("module \"org.jactr.modules.pm.visual.six.DefaultVisualModule6\"[]");
    _builder.newLine();
    _builder.append("module \"org.jactr.modules.pm.aural.six.DefaultAuralModule6\"[]");
    _builder.newLine();
    _builder.append("module \"org.jactr.modules.pm.vocal.six.DefaultVocalModule6\"[]");
    _builder.newLine();
    _builder.append("module \"org.jactr.modules.pm.motor.six.DefaultMotorModule6\"[]");
    _builder.newLine();
    _builder.append("module \"org.jactr.core.module.random.six.DefaultRandomModule\"[]");
    _builder.newLine();
    _builder.append("   ");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("buffers {");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("@Override");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("goal {} [");
    _builder.newLine();
    _builder.append("     ");
    _builder.append("\"Activation\"              : \"1\"");
    _builder.newLine();
    _builder.append("     ");
    _builder.append("\"StrictHarvestingEnabled\" : \"false\" ]");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("}");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("}[");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("\"EnablePersistentExecution\" : \"true\"");
    _builder.newLine();
    _builder.append("   ");
    _builder.append("\"EnableUnusedCycleSkipping\" : \"false\"");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("]");
    _builder.newLine();
    return _builder;
  }
}
