/**
 * generated by Xtext 2.33.0.M1
 */
package org.jactr.io2.jactr.modelFragment.impl;

import org.eclipse.emf.ecore.EClass;

import org.jactr.io2.jactr.modelFragment.ModelFragmentPackage;
import org.jactr.io2.jactr.modelFragment.OrSlot;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Or Slot</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class OrSlotImpl extends BooleanOperationImpl implements OrSlot
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected OrSlotImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ModelFragmentPackage.Literals.OR_SLOT;
  }

} //OrSlotImpl
