/**
 * generated by Xtext 2.25.0
 */
package org.jactr.io2.jactr.modelFragment.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.jactr.io2.jactr.modelFragment.ModelFragmentPackage;
import org.jactr.io2.jactr.modelFragment.ProductionAction;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Production Action</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ProductionActionImpl extends MinimalEObjectImpl.Container implements ProductionAction
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ProductionActionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ModelFragmentPackage.Literals.PRODUCTION_ACTION;
  }

} //ProductionActionImpl
