/**
 * generated by Xtext 2.16.0
 */
package org.jactr.io2.jactr.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.jactr.io2.jactr.ModelFragmentRuntimeModule;
import org.jactr.io2.jactr.ModelFragmentStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class ModelFragmentIdeSetup extends ModelFragmentStandaloneSetup {
  @Override
  public Injector createInjector() {
    ModelFragmentRuntimeModule _modelFragmentRuntimeModule = new ModelFragmentRuntimeModule();
    ModelFragmentIdeModule _modelFragmentIdeModule = new ModelFragmentIdeModule();
    return Guice.createInjector(Modules2.mixin(_modelFragmentRuntimeModule, _modelFragmentIdeModule));
  }
}
