/*
 * generated by Xtext 2.25.0
 */
package org.jactr.io2.jactr.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractModelFragmentScopeProvider extends DelegatingScopeProvider {
}
