/*
 * generated by Xtext 2.25.0
 */
package org.jactr.io2.jactr.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.jactr.io2.jactr.ui.internal.JactrActivator;

public class ModelFragmentUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return JactrActivator.getInstance().getInjector("org.jactr.io2.jactr.ModelFragment");
	}

}
